module ApplicationHelper # rubocop:disable ModuleLength
  # helper_method :resource_name, :resource, :devise_mapping

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def world_blocks
    [
      ['World', :world_countries],
      ['Europe', :european_countries],
      ['Asia and Oceania', :asian_countries],
      ['Africa', :african_countries],
      ['North America', :na_countries],
      ['South America', :sa_countries],
      ['OECD', :oecd_countries],
      ['ASEAN', :asean_countries]
    ]
  end

  def countries # rubocop:disable MethodLength
    {
      world_countries:
          [
            { name: 'Afghanistan', code: 'AF' },
            { name: 'Åland Islands', code: 'AX' },
            { name: 'Albania', code: 'AL' },
            { name: 'Algeria', code: 'DZ' },
            { name: 'American Samoa', code: 'AS' },
            { name: 'AndorrA', code: 'AD' },
            { name: 'Angola', code: 'AO' },
            { name: 'Anguilla', code: 'AI' },
            { name: 'Antarctica', code: 'AQ' },
            { name: 'Antigua and Barbuda', code: 'AG' },
            { name: 'Argentina', code: 'AR' },
            { name: 'Armenia', code: 'AM' },
            { name: 'Aruba', code: 'AW' },
            { name: 'Australia', code: 'AU' },
            { name: 'Austria', code: 'AT' },
            { name: 'Azerbaijan', code: 'AZ' },
            { name: 'Bahamas', code: 'BS' },
            { name: 'Bahrain', code: 'BH' },
            { name: 'Bangladesh', code: 'BD' },
            { name: 'Barbados', code: 'BB' },
            { name: 'Belarus', code: 'BY' },
            { name: 'Belgium', code: 'BE' },
            { name: 'Belize', code: 'BZ' },
            { name: 'Benin', code: 'BJ' },
            { name: 'Bermuda', code: 'BM' },
            { name: 'Bhutan', code: 'BT' },
            { name: 'Bolivia', code: 'BO' },
            { name: 'Bosnia and Herzegovina', code: 'BA' },
            { name: 'Botswana', code: 'BW' },
            { name: 'Bouvet Island', code: 'BV' },
            { name: 'Brazil', code: 'BR' },
            { name: 'British Indian Ocean Territory', code: 'IO' },
            { name: 'Brunei Darussalam', code: 'BN' },
            { name: 'Bulgaria', code: 'BG' },
            { name: 'Burkina Faso', code: 'BF' },
            { name: 'Burundi', code: 'BI' },
            { name: 'Cambodia', code: 'KH' },
            { name: 'Cameroon', code: 'CM' },
            { name: 'Canada', code: 'CA' },
            { name: 'Cape Verde', code: 'CV' },
            { name: 'Cayman Islands', code: 'KY' },
            { name: 'Central African Republic', code: 'CF' },
            { name: 'Chad', code: 'TD' },
            { name: 'Chile', code: 'CL' },
            { name: 'China', code: 'CN' },
            { name: 'Christmas Island', code: 'CX' },
            { name: 'Cocos (Keeling) Islands', code: 'CC' },
            { name: 'Colombia', code: 'CO' },
            { name: 'Comoros', code: 'KM' },
            { name: 'Congo', code: 'CG' },
            { name: 'Congo, The Democratic Republic of the', code: 'CD' },
            { name: 'Cook Islands', code: 'CK' },
            { name: 'Costa Rica', code: 'CR' },
            { name: 'Cote D\'Ivoire', code: 'CI' },
            { name: 'Croatia', code: 'HR' },
            { name: 'Cuba', code: 'CU' },
            { name: 'Cyprus', code: 'CY' },
            { name: 'Czech Republic', code: 'CZ' },
            { name: 'Denmark', code: 'DK' },
            { name: 'Djibouti', code: 'DJ' },
            { name: 'Dominica', code: 'DM' },
            { name: 'Dominican Republic', code: 'DO' },
            { name: 'Ecuador', code: 'EC' },
            { name: 'Egypt', code: 'EG' },
            { name: 'El Salvador', code: 'SV' },
            { name: 'Equatorial Guinea', code: 'GQ' },
            { name: 'Eritrea', code: 'ER' },
            { name: 'Estonia', code: 'EE' },
            { name: 'Ethiopia', code: 'ET' },
            { name: 'Falkland Islands (Malvinas)', code: 'FK' },
            { name: 'Faroe Islands', code: 'FO' },
            { name: 'Fiji', code: 'FJ' },
            { name: 'Finland', code: 'FI' },
            { name: 'France', code: 'FR' },
            { name: 'French Guiana', code: 'GF' },
            { name: 'French Polynesia', code: 'PF' },
            { name: 'French Southern Territories', code: 'TF' },
            { name: 'Gabon', code: 'GA' },
            { name: 'Gambia', code: 'GM' },
            { name: 'Georgia', code: 'GE' },
            { name: 'Germany', code: 'DE' },
            { name: 'Ghana', code: 'GH' },
            { name: 'Gibraltar', code: 'GI' },
            { name: 'Greece', code: 'GR' },
            { name: 'Greenland', code: 'GL' },
            { name: 'Grenada', code: 'GD' },
            { name: 'Guadeloupe', code: 'GP' },
            { name: 'Guam', code: 'GU' },
            { name: 'Guatemala', code: 'GT' },
            { name: 'Guernsey', code: 'GG' },
            { name: 'Guinea', code: 'GN' },
            { name: 'Guinea-Bissau', code: 'GW' },
            { name: 'Guyana', code: 'GY' },
            { name: 'Haiti', code: 'HT' },
            { name: 'Heard Island and Mcdonald Islands', code: 'HM' },
            { name: 'Holy See (Vatican City State)', code: 'VA' },
            { name: 'Honduras', code: 'HN' },
            { name: 'Hong Kong', code: 'HK' },
            { name: 'Hungary', code: 'HU' },
            { name: 'Iceland', code: 'IS' },
            { name: 'India', code: 'IN' },
            { name: 'Indonesia', code: 'ID' },
            { name: 'Iran, Islamic Republic Of', code: 'IR' },
            { name: 'Iraq', code: 'IQ' },
            { name: 'Ireland', code: 'IE' },
            { name: 'Isle of Man', code: 'IM' },
            { name: 'Israel', code: 'IL' },
            { name: 'Italy', code: 'IT' },
            { name: 'Jamaica', code: 'JM' },
            { name: 'Japan', code: 'JP' },
            { name: 'Jersey', code: 'JE' },
            { name: 'Jordan', code: 'JO' },
            { name: 'Kazakhstan', code: 'KZ' },
            { name: 'Kenya', code: 'KE' },
            { name: 'Kiribati', code: 'KI' },
            { name: 'Korea, Democratic People\'S Republic of', code: 'KP' },
            { name: 'Korea, Republic of', code: 'KR' },
            { name: 'Kuwait', code: 'KW' },
            { name: 'Kyrgyzstan', code: 'KG' },
            { name: 'Lao People\'S Democratic Republic', code: 'LA' },
            { name: 'Latvia', code: 'LV' },
            { name: 'Lebanon', code: 'LB' },
            { name: 'Lesotho', code: 'LS' },
            { name: 'Liberia', code: 'LR' },
            { name: 'Libyan Arab Jamahiriya', code: 'LY' },
            { name: 'Liechtenstein', code: 'LI' },
            { name: 'Lithuania', code: 'LT' },
            { name: 'Luxembourg', code: 'LU' },
            { name: 'Macao', code: 'MO' },
            { name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK' },
            { name: 'Madagascar', code: 'MG' },
            { name: 'Malawi', code: 'MW' },
            { name: 'Malaysia', code: 'MY' },
            { name: 'Maldives', code: 'MV' },
            { name: 'Mali', code: 'ML' },
            { name: 'Malta', code: 'MT' },
            { name: 'Marshall Islands', code: 'MH' },
            { name: 'Martinique', code: 'MQ' },
            { name: 'Mauritania', code: 'MR' },
            { name: 'Mauritius', code: 'MU' },
            { name: 'Mayotte', code: 'YT' },
            { name: 'Mexico', code: 'MX' },
            { name: 'Micronesia, Federated States of', code: 'FM' },
            { name: 'Moldova, Republic of', code: 'MD' },
            { name: 'Monaco', code: 'MC' },
            { name: 'Mongolia', code: 'MN' },
            { name: 'Montserrat', code: 'MS' },
            { name: 'Morocco', code: 'MA' },
            { name: 'Mozambique', code: 'MZ' },
            { name: 'Myanmar', code: 'MM' },
            { name: 'Namibia', code: 'NA' },
            { name: 'Nauru', code: 'NR' },
            { name: 'Nepal', code: 'NP' },
            { name: 'Netherlands', code: 'NL' },
            { name: 'Netherlands Antilles', code: 'AN' },
            { name: 'New Caledonia', code: 'NC' },
            { name: 'New Zealand', code: 'NZ' },
            { name: 'Nicaragua', code: 'NI' },
            { name: 'Niger', code: 'NE' },
            { name: 'Nigeria', code: 'NG' },
            { name: 'Niue', code: 'NU' },
            { name: 'Norfolk Island', code: 'NF' },
            { name: 'Northern Mariana Islands', code: 'MP' },
            { name: 'Norway', code: 'NO' },
            { name: 'Oman', code: 'OM' },
            { name: 'Pakistan', code: 'PK' },
            { name: 'Palau', code: 'PW' },
            { name: 'Palestinian Territory, Occupied', code: 'PS' },
            { name: 'Panama', code: 'PA' },
            { name: 'Papua New Guinea', code: 'PG' },
            { name: 'Paraguay', code: 'PY' },
            { name: 'Peru', code: 'PE' },
            { name: 'Philippines', code: 'PH' },
            { name: 'Pitcairn', code: 'PN' },
            { name: 'Poland', code: 'PL' },
            { name: 'Portugal', code: 'PT' },
            { name: 'Puerto Rico', code: 'PR' },
            { name: 'Qatar', code: 'QA' },
            { name: 'Reunion', code: 'RE' },
            { name: 'Romania', code: 'RO' },
            { name: 'Russian Federation', code: 'RU' },
            { name: 'RWANDA', code: 'RW' },
            { name: 'Saint Helena', code: 'SH' },
            { name: 'Saint Kitts and Nevis', code: 'KN' },
            { name: 'Saint Lucia', code: 'LC' },
            { name: 'Saint Pierre and Miquelon', code: 'PM' },
            { name: 'Saint Vincent and the Grenadines', code: 'VC' },
            { name: 'Samoa', code: 'WS' },
            { name: 'San Marino', code: 'SM' },
            { name: 'Sao Tome and Principe', code: 'ST' },
            { name: 'Saudi Arabia', code: 'SA' },
            { name: 'Senegal', code: 'SN' },
            { name: 'Serbia and Montenegro', code: 'CS' },
            { name: 'Seychelles', code: 'SC' },
            { name: 'Sierra Leone', code: 'SL' },
            { name: 'Singapore', code: 'SG' },
            { name: 'Slovakia', code: 'SK' },
            { name: 'Slovenia', code: 'SI' },
            { name: 'Solomon Islands', code: 'SB' },
            { name: 'Somalia', code: 'SO' },
            { name: 'South Africa', code: 'ZA' },
            { name: 'South Georgia and the South Sandwich Islands', code: 'GS' },
            { name: 'Spain', code: 'ES' },
            { name: 'Sri Lanka', code: 'LK' },
            { name: 'Sudan', code: 'SD' },
            { name: 'Suriname', code: 'SR' },
            { name: 'Svalbard and Jan Mayen', code: 'SJ' },
            { name: 'Swaziland', code: 'SZ' },
            { name: 'Sweden', code: 'SE' },
            { name: 'Switzerland', code: 'CH' },
            { name: 'Syrian Arab Republic', code: 'SY' },
            { name: 'Taiwan, Province of China', code: 'TW' },
            { name: 'Tajikistan', code: 'TJ' },
            { name: 'Tanzania, United Republic of', code: 'TZ' },
            { name: 'Thailand', code: 'TH' },
            { name: 'Timor-Leste', code: 'TL' },
            { name: 'Togo', code: 'TG' },
            { name: 'Tokelau', code: 'TK' },
            { name: 'Tonga', code: 'TO' },
            { name: 'Trinidad and Tobago', code: 'TT' },
            { name: 'Tunisia', code: 'TN' },
            { name: 'Turkey', code: 'TR' },
            { name: 'Turkmenistan', code: 'TM' },
            { name: 'Turks and Caicos Islands', code: 'TC' },
            { name: 'Tuvalu', code: 'TV' },
            { name: 'Uganda', code: 'UG' },
            { name: 'Ukraine', code: 'UA' },
            { name: 'United Arab Emirates', code: 'AE' },
            { name: 'United Kingdom', code: 'GB' },
            { name: 'United States', code: 'US' },
            { name: 'United States Minor Outlying Islands', code: 'UM' },
            { name: 'Uruguay', code: 'UY' },
            { name: 'Uzbekistan', code: 'UZ' },
            { name: 'Vanuatu', code: 'VU' },
            { name: 'Venezuela', code: 'VE' },
            { name: 'Viet Nam', code: 'VN' },
            { name: 'Virgin Islands, British', code: 'VG' },
            { name: 'Virgin Islands, U.S.', code: 'VI' },
            { name: 'Wallis and Futuna', code: 'WF' },
            { name: 'Western Sahara', code: 'EH' },
            { name: 'Yemen', code: 'YE' },
            { name: 'Zambia', code: 'ZM' },
            { name: 'Zimbabwe', code: 'ZW' }
          ],
      european_countries: [
        { name: 'Belarus', code: 'BY' },
        { name: 'Bulgaria', code: 'BG' },
        { name: 'Czech Republic', code: 'CZ' },
        { name: 'Hungary', code: 'HU' },
        { name: 'Moldova, Republic of', code: 'MD' },
        { name: 'Poland', code: 'PL' },
        { name: 'Romania', code: 'RO' },
        { name: 'Russian Federation', code: 'RU' },
        { name: 'Slovakia', code: 'SK' },
        { name: 'Ukraine', code: 'UA' },
        { name: 'Denmark', code: 'DK' },
        { name: 'Estonia', code: 'EE' },
        { name: 'Faroe Islands', code: 'FO' },
        { name: 'Finland', code: 'FI' },
        { name: 'Greenland', code: 'GL' },
        { name: 'Iceland', code: 'IS' },
        { name: 'Ireland', code: 'IE' },
        { name: 'Latvia', code: 'LV' },
        { name: 'Lithuania', code: 'LT' },
        { name: 'United Kingdom', code: 'GB' },
        { name: 'Norway', code: 'NO' },
        { name: 'Sweden', code: 'SE' },
        { name: 'Albania', code: 'AL' },
        { name: 'AndorrA', code: 'AD' },
        { name: 'Bosnia and Herzegovina', code: 'BA' },
        { name: 'Croatia', code: 'HR' },
        { name: 'Cyprus', code: 'CY' },
        { name: 'Gibraltar', code: 'GI' },
        { name: 'Greece', code: 'GR' },
        { name: 'Holy See (Vatican City State)', code: 'VA' },
        { name: 'Italy', code: 'IT' },
        { name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK' },
        { name: 'Malta', code: 'MT' },
        { name: 'Serbia and Montenegro', code: 'CS' },
        { name: 'Portugal', code: 'PT' },
        { name: 'San Marino', code: 'SM' },
        { name: 'Slovenia', code: 'SI' },
        { name: 'Spain', code: 'ES' },
        { name: 'Turkey', code: 'TR' },
        { name: 'Austria', code: 'AT' },
        { name: 'Belgium', code: 'BE' },
        { name: 'France', code: 'FR' },
        { name: 'Germany', code: 'DE' },
        { name: 'Liechtenstein', code: 'LI' },
        { name: 'Luxembourg', code: 'LU' },
        { name: 'Monaco', code: 'MC' },
        { name: 'Netherlands', code: 'NL' },
        { name: 'Switzerland', code: 'CH' }
      ],
      asian_countries: [
        { name: 'Australia', code: 'AU' },
        { name: 'China', code: 'CN' },
        { name: 'Hong Kong', code: 'HK' },
        { name: 'Macao', code: 'MO' },
        { name: 'Japan', code: 'JP' },
        { name: 'Korea, Democratic People\'S Republic of', code: 'KP' },
        { name: 'Korea, Republic of', code: 'KR' },
        { name: 'Mongolia', code: 'MN' },
        { name: 'Taiwan, Province of China', code: 'TW' },
        { name: 'Russian Federation', code: 'RU' },
        { name: 'Afghanistan', code: 'AF' },
        { name: 'Bangladesh', code: 'BD' },
        { name: 'Bhutan', code: 'BT' },
        { name: 'India', code: 'IN' },
        { name: 'Iran, Islamic Republic Of', code: 'IR' },
        { name: 'Kazakhstan', code: 'KZ' },
        { name: 'Kyrgyzstan', code: 'KG' },
        { name: 'Maldives', code: 'MV' },
        { name: 'Nepal', code: 'NP' },
        { name: 'Pakistan', code: 'PK' },
        { name: 'Sri Lanka', code: 'LK' },
        { name: 'Tajikistan', code: 'TJ' },
        { name: 'Turkmenistan', code: 'TM' },
        { name: 'Uzbekistan', code: 'UZ' },
        { name: 'Brunei Darussalam', code: 'BN' },
        { name: 'Cambodia', code: 'KH' },
        { name: 'Indonesia', code: 'ID' },
        { name: 'Lao People\'S Democratic Republic', code: 'LA' },
        { name: 'Malaysia', code: 'MY' },
        { name: 'Myanmar', code: 'MM' },
        { name: 'Philippines', code: 'PH' },
        { name: 'Singapore', code: 'SG' },
        { name: 'Thailand', code: 'TH' },
        { name: 'Timor-Leste', code: 'TL' },
        { name: 'Viet Nam', code: 'VN' },
        { name: 'Armenia', code: 'AM' },
        { name: 'Azerbaijan', code: 'AZ' },
        { name: 'Bahrain', code: 'BH' },
        { name: 'Cyprus', code: 'CY' },
        { name: 'Georgia', code: 'GE' },
        { name: 'Iraq', code: 'IQ' },
        { name: 'Israel', code: 'IL' },
        { name: 'Jordan', code: 'JO' },
        { name: 'Kuwait', code: 'KW' },
        { name: 'Lebanon', code: 'LB' },
        { name: 'Oman', code: 'OM' },
        { name: 'Palestinian Territory, Occupied', code: 'PS' },
        { name: 'Qatar', code: 'QA' },
        { name: 'Saudi Arabia', code: 'SA' },
        { name: 'Syrian Arab Republic', code: 'SY' },
        { name: 'Turkey', code: 'TR' },
        { name: 'United Arab Emirates', code: 'AE' },
        { name: 'Yemen', code: 'YE' }
      ],
      african_countries: [
        { name: 'Burundi', code: 'BI' },
        { name: 'Comoros', code: 'KM' },
        { name: 'Djibouti', code: 'DJ' },
        { name: 'Eritrea', code: 'ER' },
        { name: 'Ethiopia', code: 'ET' },
        { name: 'Kenya', code: 'KE' },
        { name: 'Madagascar', code: 'MG' },
        { name: 'Malawi', code: 'MW' },
        { name: 'Mauritius', code: 'MU' },
        { name: 'Mozambique', code: 'MZ' },
        { name: 'Reunion', code: 'RE' },
        { name: 'RWANDA', code: 'RW' },
        { name: 'Seychelles', code: 'SC' },
        { name: 'Somalia', code: 'SO' },
        { name: 'Tanzania, United Republic of', code: 'TZ' },
        { name: 'Uganda', code: 'UG' },
        { name: 'Zambia', code: 'ZM' },
        { name: 'Zimbabwe', code: 'ZW' },
        { name: 'Angola', code: 'AO' },
        { name: 'Cameroon', code: 'CM' },
        { name: 'Central African Republic', code: 'CF' },
        { name: 'Chad', code: 'TD' },
        { name: 'Congo', code: 'CG' },
        { name: 'Congo, The Democratic Republic of the', code: 'CD' },
        { name: 'Equatorial Guinea', code: 'GQ' },
        { name: 'Gabon', code: 'GA' },
        { name: 'Sao Tome and Principe', code: 'ST' },
        { name: 'Algeria', code: 'DZ' },
        { name: 'Egypt', code: 'EG' },
        { name: 'Libyan Arab Jamahiriya', code: 'LY' },
        { name: 'Morocco', code: 'MA' },
        { name: 'Sudan', code: 'SD' },
        { name: 'Tunisia', code: 'TN' },
        { name: 'Western Sahara', code: 'EH' },
        { name: 'Botswana', code: 'BW' },
        { name: 'Lesotho', code: 'LS' },
        { name: 'Namibia', code: 'NA' },
        { name: 'South Africa', code: 'ZA' },
        { name: 'Swaziland', code: 'SZ' },
        { name: 'Benin', code: 'BJ' },
        { name: 'Burkina Faso', code: 'BF' },
        { name: 'Cape Verde', code: 'CV' },
        { name: 'Cote D\'Ivoire', code: 'CI' },
        { name: 'Gambia', code: 'GM' },
        { name: 'Ghana', code: 'GH' },
        { name: 'Guinea', code: 'GN' },
        { name: 'Guinea-Bissau', code: 'GW' },
        { name: 'Liberia', code: 'LR' },
        { name: 'Mali', code: 'ML' },
        { name: 'Mauritania', code: 'MR' },
        { name: 'Niger', code: 'NE' },
        { name: 'Nigeria', code: 'NG' },
        { name: 'Saint Helena', code: 'SH' },
        { name: 'Senegal', code: 'SN' },
        { name: 'Sierra Leone', code: 'SL' },
        { name: 'Togo', code: 'TG' }
      ],
      na_countries: [
        { name: 'United States', code: 'US' },
        { name: 'Canada', code: 'CA' },
        { name: 'Mexico', code: 'MX' }
      ],
      sa_countries: [
        { name: 'Anguilla', code: 'AI' },
        { name: 'Antigua and Barbuda', code: 'AG' },
        { name: 'Aruba', code: 'AW' },
        { name: 'Bahamas', code: 'BS' },
        { name: 'Barbados', code: 'BB' },
        { name: 'Bermuda', code: 'BM' },
        { name: 'Virgin Islands, British', code: 'VG' },
        { name: 'Cayman Islands', code: 'KY' },
        { name: 'Cuba', code: 'CU' },
        { name: 'Dominica', code: 'DM' },
        { name: 'Dominican Republic', code: 'DO' },
        { name: 'Grenada', code: 'GD' },
        { name: 'Guadeloupe', code: 'GP' },
        { name: 'Haiti', code: 'HT' },
        { name: 'Jamaica', code: 'JM' },
        { name: 'Martinique', code: 'MQ' },
        { name: 'Montserrat', code: 'MS' },
        { name: 'Netherlands Antilles', code: 'AN' },
        { name: 'Puerto Rico', code: 'PR' },
        { name: 'Saint Kitts and Nevis', code: 'KN' },
        { name: 'Saint Lucia', code: 'LC' },
        { name: 'Saint Vincent and the Grenadines', code: 'VC' },
        { name: 'Trinidad and Tobago', code: 'TT' },
        { name: 'Virgin Islands, U.S.', code: 'VI' },
        { name: 'Belize', code: 'BZ' },
        { name: 'Costa Rica', code: 'CR' },
        { name: 'Guatemala', code: 'GT' },
        { name: 'Honduras', code: 'HN' },
        { name: 'Nicaragua', code: 'NI' },
        { name: 'Panama', code: 'PA' },
        { name: 'Argentina', code: 'AR' },
        { name: 'Bolivia', code: 'BO' },
        { name: 'Brazil', code: 'BR' },
        { name: 'Chile', code: 'CL' },
        { name: 'Colombia', code: 'CO' },
        { name: 'Ecuador', code: 'EC' },
        { name: 'French Guiana', code: 'GF' },
        { name: 'Guyana', code: 'GY' },
        { name: 'Paraguay', code: 'PY' },
        { name: 'Peru', code: 'PE' },
        { name: 'Suriname', code: 'SR' },
        { name: 'Uruguay', code: 'UY' },
        { name: 'Venezuela', code: 'VE' }
      ],
      oecd_countries: [
        { name: 'Australia', code: 'AU' },
        { name: 'Austria', code: 'AT' },
        { name: 'Belgium', code: 'BE' },
        { name: 'Canada', code: 'CA' },
        { name: 'Chile', code: 'CL' },
        { name: 'Czech Republic', code: 'CZ' },
        { name: 'Denmark', code: 'DK' },
        { name: 'Estonia', code: 'EE' },
        { name: 'Finland', code: 'FI' },
        { name: 'France', code: 'FR' },
        { name: 'Germany', code: 'DE' },
        { name: 'Greece', code: 'GR' },
        { name: 'Hungary', code: 'HU' },
        { name: 'Iceland', code: 'IS' },
        { name: 'Ireland', code: 'IE' },
        { name: 'Israel', code: 'IL' },
        { name: 'Italy', code: 'IT' },
        { name: 'Japan', code: 'JP' },
        { name: 'Korea, Republic of', code: 'KR' },
        { name: 'Latvia', code: 'LV' },
        { name: 'Luxembourg', code: 'LU' },
        { name: 'Mexico', code: 'MX' },
        { name: 'Netherlands', code: 'NL' },
        { name: 'New Zealand', code: 'NZ' },
        { name: 'Norway', code: 'NO' },
        { name: 'Poland', code: 'PL' },
        { name: 'Portugal', code: 'PT' },
        { name: 'Slovakia', code: 'SK' },
        { name: 'Slovenia', code: 'SI' },
        { name: 'Spain', code: 'ES' },
        { name: 'Sweden', code: 'SE' },
        { name: 'Switzerland', code: 'CH' },
        { name: 'Turkey', code: 'TR' },
        { name: 'United Kingdom', code: 'GB' },
        { name: 'United States', code: 'US' }
      ],
      asean_countries: [
        { name: 'Brunei Darussalam', code: 'BN' },
        { name: 'Cambodia', code: 'KH' },
        { name: 'Indonesia', code: 'ID' },
        { name: 'Lao People\'S Democratic Republic', code: 'LA' },
        { name: 'Malaysia', code: 'MY' },
        { name: 'Myanmar', code: 'MM' },
        { name: 'Philippines', code: 'PH' },
        { name: 'Singapore', code: 'SG' },
        { name: 'Thailand', code: 'TH' },
        { name: 'Viet Nam', code: 'VN' }
      ]
    }
  end
end
